language: rust
rust: nightly
sudo: false

before_script:
  - cargo install clippy || true
  - export PATH=$HOME/.cargo/bin:$PATH

script:
  - cargo test --all-features
  - if command -v cargo-clippy > /dev/null; then cargo clippy -- -D warnings; fi
