[package]
name = "karkinos"
version = "0.1.0"
authors = ["Chris Wong <lambda.fairy@gmail.com>"]

[dependencies]
caseless = "*"
chan-signal = "*"
env_logger = "*"
iron = "*"
lazy_static = "*"
log = "*"
logger = "*"
maud = { version = "*", features = ["iron"] }
maud_macros = "*"
mime = "*"
persistent = "*"
pulldown-cmark = "*"
router = "*"
serde = "*"
serde_derive = "*"
serde_json = "*"
staticfile = "*"
unicode-normalization = "*"
unicode-segmentation = "*"
urlencoded = "*"
