[package]
name = "karkinos"
version = "0.1.0"
authors = ["Chris Wong <lambda.fairy@gmail.com>"]

[dependencies]
iron = "*"
maud = { version = "*", features = ["iron"] }
maud_macros = "*"
mime = "*"
router = "*"
serde_json = "*"
