[package]
name = "karkinos"
version = "0.1.0"
authors = ["Chris Wong <lambda.fairy@gmail.com>"]

[dependencies]
iron = "*"
maud = { version = "*", features = ["iron"] }
maud_macros = "*"
mime = "*"
persistent = { git = "https://github.com/lfairy/persistent", branch = "from-arc" }
router = "*"
serde = "*"
serde_derive = "*"
serde_json = "*"
