[package]
name = "karkinos"
version = "0.1.0"
authors = ["Chris Wong <lambda.fairy@gmail.com>"]

[dependencies]
iron = "*"
router = "*"
serde = "*"
serde_json = "*"

[dependencies.maud]
path = "../maud/maud"

[dependencies.maud_macros]
path = "../maud/maud_macros"

[dependencies.iron-maud]
path = "../maud/iron-maud"
